apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marqo-pvc
  namespace: vb-se
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi