apiVersion: apps/v1
kind: Deployment
metadata:
  name: marqo
  namespace: vb-se
  labels:
    app: marqo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marqo
  template:
    metadata:
      labels:
        app: marqo
    spec:
      volumes:
      - name: marqo-pvc
        persistentVolumeClaim:
          claimName: marqo-pvc
      containers:
      - name: marqo
        image: marqoai/marqo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8882
          name: marqo-port
        volumeMounts:
        - name: marqo-pvc
          mountPath: /opt/vespa/marqo