apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh
  namespace: vb-se
  labels:
    app: vb-se
    component: refresh
spec:
  schedule: "0 0 * * *"  # Run every day at midnight
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: refresh
            image: ghcr.io/josh-cannot-code/docker-vb-se-refresh:latest
            env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-api-key
                  key: api-key
            - name: MARQO_HOST
              valueFrom:
                configMapKeyRef:
                  name: vb-se-config
                  key: marqo_host
            - name: CHANNELS
              valueFrom:
                configMapKeyRef:
                  name: vb-se-config
                  key: channels
