apiVersion: apps/v1
kind: Deployment
metadata:
  name: vb-se-deployment
  namespace: vb-se
  labels:
    app: vb-se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vb-se
  template:
    metadata:
      labels:
        app: vb-se
    spec:
      containers:
      - name: vb-se
        image: ghcr.io/josh-cannot-code/docker-vb-se:latest
        imagePullPolicy: Always
        env:
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-api-key
              key: api-key
        - name: ENVIRONMENT
          value: "prod"
        ports:
        - containerPort: 3002
          name: vb-se-port
        volumeMounts:
          - mountPath: /go_server/db
            name: database-volume
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: vb-se-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vb-se-service
  namespace: vb-se
spec:
  selector:
    app: vb-se
  ports:
  - name: vb-se-service-port
    protocol: TCP
    port: 80
    targetPort: vb-se-port

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vb-se-pvc
  namespace: vb-se
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn

