name: publish
on: 
  push:
    branches:
      - main
jobs:
  publish-vb-se-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the vb-se-docker-image
        run: |
          docker build ./src --tag ghcr.io/josh-cannot-code/docker-vb-se:latest
          docker push ghcr.io/josh-cannot-code/docker-vb-se:latest
  publish-vb-se-refresh-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the vb-se-refresh-docker-image
        run: |
          docker build ./src/refresh --tag ghcr.io/josh-cannot-code/docker-vb-se-refresh:latest
          docker push ghcr.io/josh-cannot-code/docker-vb-se-refresh:latest