// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "go_server/models"

func Index(videos []*models.Video) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"/static/output.css\" rel=\"stylesheet\"></head><script>\n    function updateUrlWithState(state) {\n        const url = new URL(window.location.href);\n        Object.keys(state).forEach(key => {\n            url.searchParams.set(key, state[key]);\n        });\n        history.pushState({}, '', url);\n    }\n\n    window.onload = function() {\n        const urlParams = new URLSearchParams(window.location.search);\n        const searchQuery = urlParams.get('search');\n        if (searchQuery) {\n            document.getElementById('search-bar').value = searchQuery;\n        }\n    }\n</script><body><div class=\"h-screen flex flex-col justify-between\"><h1 class=\"text-4xl md:text-5xl text-center mb-4 font-light px-4 mt-10\">Vlogbrothers Search Engine</h1><div class=\"flex justify-center items-center w-full p-4\"><form class=\"flex flex-col sm:flex-row gap-4 w-full max-w-2xl px-4\" onsubmit=\"updateUrlWithState({search: document.getElementById(&#39;search-bar&#39;).value, sorting: document.getElementById(&#39;sorting&#39;).value})\"><input id=\"search-bar\" type=\"text\" name=\"search\" placeholder=\"Search Vlogbrothers Youtube Channel\" class=\"px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full\"> <button type=\"submit\" class=\"px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors duration-200 w-full sm:w-auto\">Search</button></form></div><div class=\"text-center mb-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = VideoList(videos).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><footer class=\"bg-gray-100 border-t border-gray-200\"><div class=\"max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8\"><div class=\"flex flex-col sm:flex-row justify-between items-center gap-4 sm:gap-0\"><div class=\"text-gray-600 text-sm text-center sm:text-right\">Made with ♥️ for Jade</div><div class=\"text-gray-600 text-sm text-center sm:text-left\"><a href=\"mailto:j.dallacqua1@gmail.com\" class=\"hover:text-blue-600 transition-colors duration-200\">j.dallacqua1@gmail.com</a></div></div></div></footer></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
